add Ukrainian translation
ashutoshgngwr/noice pull request #354
Opened 2020-10-04 20:34 UTC by JekRock

### Changes
Add Ukrainian translation

### Testing
- [x] Tested on a physical device
- [ ] Added or modified unit test cases

### Others
- Fixes #0
- Connects #0

2020-10-04 20:42 UTC, JekRock commented
Also, there are a few issues I've found on a real device.
Here the text is too long to fit and it's not scrollable.
<img src="https://user-images.githubusercontent.com/5882133/95026511-67bb7200-069a-11eb-8a88-d3f716b088b0.png" height="500px"/>
Here and on the previous screenshot, the "skip" and "done" buttons aren't translated for some reason. They aren't present in the resources list though.
<img src="https://user-images.githubusercontent.com/5882133/95026545-ad783a80-069a-11eb-9484-809ad118d06e.png" height="500px"/>

2020-10-05 08:16 UTC, ashutoshgngwr requested changes
Hey @JekRock, thank you for taking the time to create this PR. I found 2 issues, please take a look at them.

Regarding the concerns that you pointed out:

> Also, there are a few issues I've found on a real device. Here the text is too long to fit and it's not scrollable.

You can rephrase the text to be shorter. User will tend to skip very long texts in the intro slides. The original intent of the message was to explain what the time slider does.

> Here and on the previous screenshot, the "skip" and "done" buttons aren't translated for some reason. They aren't present in the resources list though.

These are provided by the [AppIntro](https://github.com/AppIntro/AppIntro) library. You can create a PR in their repository to provide Ukrainian translations. See [this](https://github.com/AppIntro/AppIntro#translating-).

2020-10-05 08:46 UTC, JekRock commented on app/src/main/res/values-uk-rUA/strings.xml
> +  <string name="wind_in_chimes_of_shells">Китайський дзвіночок із мушель</string>
It was the most difficult to translate.
If I understand it correctly, it's the sound made by something that looks similar to [that](https://duckduckgo.com/?t=ffab&q=chime+of+shells&iax=images&ia=images&iai=http%3A%2F%2Fwww.quiet-corner.com%2Fwp-content%2Fuploads%2F2016%2F07%2FGreat-DIY-Seashell-Wind-Chimes-Ideas-4.jpg)
There is no short name for that thing in Ukrainian and the closest description is what I put into translation.
Russian translation has the word "Фурин" ([link](https://github.com/ashutoshgngwr/noice/blob/44fd8c85fb249727e43e7a1567b197bb5d3109ae/app/src/main/res/values-ru/strings.xml#L39)) that means "Japanese bell" (I don't agree with that translation).

I can change it to "Дзвін мушель" (bell of shells) if you think that it's a better translation for that.

2020-10-05 08:48 UTC, JekRock commented on fastlane/metadata/android/uk-UA/short_description.txt
> +Розслабтесь, покращить фокус та збільште продуктивність з мінімальним фоновим шумом
Sure, I'll rephrase the description to make it fit the 80 characters limitation

2020-10-05 08:50 UTC, JekRock commented
> You can rephrase the text to be shorter. User will tend to skip very long texts in the intro slides. The original intent of the message was to explain what the time slider does.
Got it, I'll rephrase it

> These are provided by the AppIntro library. You can create a PR in their repository to provide Ukrainian translations. See this
Thanks, I'll send them a PR with translation

2020-10-05 08:52 UTC, JekRock commented
Also, I can help with updating the Russian translation, if you don't mind

2020-10-05 08:54 UTC, ashutoshgngwr commented on app/src/main/res/values-uk-rUA/strings.xml
> +  <string name="wind_in_chimes_of_shells">Китайський дзвіночок із мушель</string>
@JekRock Can we make it _Bells of glass shells_?

2020-10-05 08:54 UTC, ashutoshgngwr commented
@JekRock Thanks for the quick response.

> Also, I can help with updating the Russian translation, if you don't mind

Yes, please. Translations are lagging behind by a lot.

2020-10-05 09:01 UTC, JekRock commented on app/src/main/res/values-uk-rUA/strings.xml
> +  <string name="wind_in_chimes_of_shells">Китайський дзвіночок із мушель</string>
I'm not sure that it sounds like _glass_ shells (I may be wrong).
But generally, yes, it's kind of similar to what you suggested.

2020-10-05 09:02 UTC, JekRock commented
> Yes, please. Translations are lagging behind by a lot.

Sure, I'll send a PR after we finish with the Ukrainian translation

2020-10-05 09:04 UTC, JekRock commented
Also, do you have a template for the featureGraphic?
I would like to add it to the translation as well.

2020-10-05 09:09 UTC, ashutoshgngwr commented
@JekRock I don't have a template. I create it at canva.com using a natural image for background. The dimensions must be 1024x500.

2020-10-05 11:38 UTC, ashutoshgngwr commented on app/src/main/res/values-uk-rUA/strings.xml
> +  <string name="wind_in_chimes_of_shells">Китайський дзвіночок із мушель</string>
Yeah right. More like metal shells. _Bell of shells_ is fine I guess!

2020-10-05 19:16 UTC, JekRock commented
@ashutoshgngwr I've made changes that we've discussed.
Also, I've added the featureGraphic for the Ukrainian translation. Let me know if it looks fine.

2020-10-05 19:18 UTC, JekRock commented
I would appriciate if you could add the "hacktoberfest-accepted" label to the PR before merging. If not, that's fine, no worries

2020-10-05 20:43 UTC, ashutoshgngwr commented
@JekRock I've added the Hacktoberfest topic to the repository so I don't think it'll be necessary but I'll add it anyways.

2020-10-05 20:44 UTC, ashutoshgngwr approved these changes

2020-10-05 20:46 UTC, merged

2020-10-06 08:35 UTC, JekRock commented
@ashutoshgngwr Thank you!